const data = {
  sofas: [
    {
      name: "Wittman",
      slug: "ray-wittman-sofa",
      category: "Sofas",
      image: "/images/sofas/brown6.jpg",
      price: 899.99,
      brief: "3 seater sofa velvet fabric",
      measure: "80 x 60 x 170 cm",
      countInStock: 5,
      brand: "Kapiton",
      rating: 3.5,
      numReviews: 10,
      description:
        "Available in 3 incredible colors: brown, blue, salmon. This sofa is made with fully covered velvet fabric. It comes with 6 cushions, ideal for small but cozy rooms. Only 5 exclusive copies throughout the country.",
    },
    {
      name: "Ovall",
      slug: "ovall-red-sofa",
      category: "Sofas",
      image: "/images/sofas/redsofa2.jpg",
      price: 850.5,
      brief: "2 seater sofa",
      measure: "80 x 60 x 180 cm",
      countInStock: 7,
      brand: "Kapiton",
      rating: 4.5,
      numReviews: 6,
      description: "",
    },
    {
      name: "Maxalto",
      slug: "maxalto-black-sofa",
      category: "Sofas",
      image: "/images/sofas/sofablack5.jpg",
      price: 1050,
      brief: "2 seater black sofa",
      measure: "80 x 60 x 190 cm",
      countInStock: 5,
      brand: "Kapiton",
      rating: 4.5,
      numReviews: 6,
      description:
        "This unique piece designed for offices and rooms. covered in bonder leather with 10 grams of foam at the base and 4 and 3 grams at the top. available in black",
    },
    {
      name: "Solpuri",
      slug: "solpuri-blue-sofa",
      category: "Sofas",
      image: "/images/sofas/sofablue7.jpg",
      price: 850,
      brief: "3 seater sofa",
      measure: "80 x 60 x 200 cm",
      countInStock: 8,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 15,
      description:
        "Outdoor lounge sofa Frame  white/anthracite aluminum - Table top - ceramic teak aluminum. Available in 3 beautiful colors: Yellow, Blue and Pink.",
    },
    {
      name: "Marelli",
      slug: "marelli-blue-sofa",
      category: "Sofas",
      image: "/images/sofas/sofablue9.jpg",
      price: 850,
      brief: "3 seater sofa with cushions",
      measure: "80 x 60 x 190 cm",
      countInStock: 7,
      brand: "Kapiton",
      rating: 4.5,
      numReviews: 6,
      description:
        "Luxury sofa collection for living rooms and/or offices and bedrooms. Jakar fabric and ultra soft foam on top. 2 cushions for each side and 4 cushions for the back. available in blue, gray and beige",
    },
    {
      name: "Macazz",
      slug: "macazz-cream-sofa",
      category: "Sofas",
      image: "/images/sofas/sofacream3.jpg",
      price: 750,
      brief: "2 seater sofa color cream",
      measure: "80 x 60 x 180 cm",
      countInStock: 10,
      brand: "Kapiton",
      rating: 4.1,
      numReviews: 3,
      description:
        "Beautiful sofa covered in jakar fabric, gray beige and black, 10 units available nationwide. 4 soft cushions on the back",
    },
    {
      name: " Vibieffe",
      slug: "vibieffe-cream-sofa",
      category: "Sofas",
      image: "/images/sofas/sofacream4.jpg",
      price: 1250,
      brief: "L sofa left and right",
      measure: "80 x 60 x 120 x 210 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 4,
      description:
        "Sofa in L single color in beige, ideal for large rooms. Armed with 4 large cushions on the back and 4 small decorative cushions on the front. Available in gray and L right or left",
    },
    {
      name: "Island",
      slug: "island-red-sofa",
      category: "Sofas",
      image: "/images/sofas/sofared8.jpg",
      price: 1098,
      brief: "2 seater sofa",
      measure: "80 x 60 x 195 cm",
      countInStock: 7,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 10,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
  ],
};

export default data;
