const data = {
  sofas: [
    {
      _id: "1",
      name: "Wittman",
      slug: "ray-wittman-sofa",
      category: "Sofas",
      image: "/images/sofas/brown6.jpg",
      price: 599.99,
      brief: "3 seater sofa velvet fabric",
      measure: "80 x 60 x 170 cm",
      countInStock: 2,
      brand: "Kapiton",
      rating: 4,
      numReviews: 2,
      description:
        "Available in 3 incredible colors: brown, blue, salmon. This sofa is made with fully covered velvet fabric. It comes with 6 cushions, ideal for small but cozy rooms. Only 5 exclusive copies throughout the country.",
    },
    {
      _id: "2",
      name: "Ovall",
      slug: "ovall-red-sofa",
      category: "Sofas",
      image: "/images/sofas/redsofa2.jpg",
      price: 650.5,
      brief: "2 seater sofa",
      measure: "80 x 60 x 180 cm",
      countInStock: 0,
      brand: "Kapiton",
      rating: 3,
      numReviews: 3,
      description:
        "Oval sofa design in different colors. Lined in velvet and jakar fabric. available for immediate delivery",
    },
    {
      _id: "3",
      name: "Maxalto",
      slug: "maxalto-black-sofa",
      category: "Sofas",
      image: "/images/sofas/sofablack5.jpg",
      price: 756.99,
      brief: "2 seater black sofa",
      measure: "80 x 60 x 190 cm",
      countInStock: 5,
      brand: "Kapiton",
      rating: 4.5,
      numReviews: 6,
      description:
        "This unique piece designed for offices and rooms. covered in bonder leather with 10 grams of foam at the base and 4 and 3 grams at the top. available in black",
    },
    {
      _id: "4",
      name: "Solpuri",
      slug: "solpuri-blue-sofa",
      category: "Sofas",
      image: "/images/sofas/sofablue7.jpg",
      price: 849.99,
      brief: "3 seater sofa",
      measure: "80 x 60 x 200 cm",
      countInStock: 8,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 5,
      description:
        "Outdoor lounge sofa Frame  white/anthracite aluminum - Table top - ceramic teak aluminum. Available in 3 beautiful colors: Yellow, Blue and Pink.",
    },
    {
      _id: "5",
      name: "Marelli",
      slug: "marelli-blue-sofa",
      category: "Sofas",
      image: "/images/sofas/sofablue9.jpg",
      price: 850,
      brief: "3 seater sofa with cushions",
      measure: "80 x 60 x 190 cm",
      countInStock: 7,
      brand: "Kapiton",
      rating: 4.5,
      numReviews: 6,
      description:
        "Luxury sofa collection for living rooms and/or offices and bedrooms. Jakar fabric and ultra soft foam on top. 2 cushions for each side and 4 cushions for the back. available in blue, gray and beige",
    },
    {
      _id: "6",
      name: "Macazz",
      slug: "macazz-cream-sofa",
      category: "Sofas",
      image: "/images/sofas/sofacream3.jpg",
      price: 750,
      brief: "2 seater sofa color cream",
      measure: "80 x 60 x 180 cm",
      countInStock: 10,
      brand: "Kapiton",
      rating: 4.1,
      numReviews: 3,
      description:
        "Beautiful sofa covered in jakar fabric, gray beige and black, 10 units available nationwide. 4 soft cushions on the back",
    },
    {
      _id: "7",
      name: " Vibieffe",
      slug: "vibieffe-cream-sofa",
      category: "Sofas",
      image: "/images/sofas/sofacream4.jpg",
      price: 1250,
      brief: "L sofa left and right",
      measure: "80 x 60 x 120 x 210 cm",
      countInStock: 10,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 4,
      description:
        "Sofa in L single color in beige, ideal for large rooms. Armed with 4 large cushions on the back and 4 small decorative cushions on the front. Available right and left sides.",
    },
    {
      _id: "8",
      name: "Island",
      slug: "island-red-sofa",
      category: "Sofas",
      image: "/images/sofas/sofared8.jpg",
      price: 1098,
      brief: "2 seater sofa",
      measure: "80 x 60 x 195 cm",
      countInStock: 3,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 10,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
  ],
  chairs: [
    {
      _id: "9",
      name: "Fredericia",
      slug: "spanish-chair",
      category: "chairs",
      image: "/images/chairs/chair1.jpg",
      price: 399.99,
      brief: "Spanish chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 3,
      brand: "Kapiton",
      rating: 3,
      numReviews: 5,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
    {
      _id: "10",
      name: "Swoon Chair",
      slug: "swoon-chair",
      category: "chairs",
      image: "/images/chairs/chair2.jpg",
      price: 599,
      brief: "Swoon chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 3,
      description:
        "This beautiful easy chair is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with in wood finish.",
    },
    {
      _id: "11",
      name: "Leya",
      slug: "leya-chair",
      category: "chairs",
      image: "/images/chairs/chair3.jpg",
      price: 699.99,
      brief: "Leya chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 5,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
    {
      _id: "12",
      name: "Colony",
      slug: "colony-chair",
      category: "chairs",
      image: "/images/chairs/chair4.jpg",
      price: 499.99,
      brief: "colony chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
    {
      _id: "13",
      name: "Nut Lounge",
      slug: "nut-lounge-chair",
      category: "chairs",
      image: "/images/chairs/chair5.jpg",
      price: 399.99,
      brief: "nut lounge chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4,
      numReviews: 10,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
    {
      _id: "14",
      name: "Era",
      slug: "era-chair",
      category: "chairs",
      image: "/images/chairs/chair6.jpg",
      price: 599.99,
      brief: "colony chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 3,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
    {
      _id: "15",
      name: "Havana",
      slug: "havana-chair",
      category: "chairs",
      image: "/images/chairs/chair7.jpg",
      price: 599.99,
      brief: "colony chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 3.5,
      numReviews: 8,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
    {
      _id: "16",
      name: "Divantis",
      slug: "divantis-chair",
      category: "chairs",
      image: "/images/chairs/chair8.jpg",
      price: 499.99,
      brief: "colony chair",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description:
        "This beautiful sofa is made with soft jakar fabric, filled with soft foam, padded on the sides and back, legs with a metallic finish.",
    },
  ],
  tables: [
    {
      _id: "17",
      name: "Gianni",
      slug: "gianni-table",
      category: "tables",
      image: "/images/tables/table1.jpg",
      price: 359.99,
      brief: "gianni table an dante",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
    {
      _id: "18",
      name: "Palatti",
      slug: "palatti-table",
      category: "tables",
      image: "/images/tables/table2.jpg",
      price: 329.99,
      brief: "palatti table an dante",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
    {
      _id: "19",
      name: "Pyramid",
      slug: "pyramid-table",
      category: "tables",
      image: "/images/tables/table3.jpg",
      price: 229.99,
      brief: "pyramid table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
    {
      _id: "20",
      name: "Copenhague",
      slug: "copenhague-table",
      category: "tables",
      image: "/images/tables/table4.jpg",
      price: 199.99,
      brief: "copenhague table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
    {
      _id: "21",
      name: "Solar",
      slug: "solar-table",
      category: "tables",
      image: "/images/tables/table5.jpg",
      price: 229.99,
      brief: "solar table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 2.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
    {
      _id: "22",
      name: "Ademar",
      slug: "ademar-table",
      category: "tables",
      image: "/images/tables/table6.jpg",
      price: 399.99,
      brief: "ademar table",
      measure: "80 x 60 x 195 cm",
      countInStock: 3,
      brand: "Kapiton",
      rating: 4,
      numReviews: 3,
      description: "This beautiful sofa is made",
    },
    {
      _id: "23",
      name: "Join",
      slug: "join-table",
      category: "tables",
      image: "/images/tables/table7.jpg",
      price: 349.99,
      brief: "join table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 6,
      description: "This beautiful sofa is made",
    },
    {
      _id: "24",
      name: "Jeff",
      slug: "jeff-table",
      category: "tables",
      image: "/images/tables/table8.jpg",
      price: 299.99,
      brief: "jeff table",
      measure: "80 x 60 x 195 cm",
      countInStock: 5,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 5,
      description: "This beautiful sofa is made",
    },
    {
      _id: "25",
      name: "Nesso",
      slug: "nesso-table",
      category: "tables",
      image: "/images/tables/table9.jpg",
      price: 219.99,
      brief: "nesso table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 15,
      description: "This beautiful sofa is made",
    },
    {
      _id: "26",
      name: "Carl",
      slug: "carl-table",
      category: "tables",
      image: "/images/tables/table10.jpg",
      price: 159.99,
      brief: "carl table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
    {
      _id: "27",
      name: "Mizar",
      slug: "mizar-table",
      category: "tables",
      image: "/images/tables/table11.jpg",
      price: 289.99,
      brief: "mizar table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 3.9,
      numReviews: 6,
      description: "This beautiful sofa is made",
    },
    {
      _id: "28",
      name: "Victor",
      slug: "victor-table",
      category: "tables",
      image: "/images/tables/table12.jpg",
      price: 399.99,
      brief: "victor table",
      measure: "80 x 60 x 195 cm",
      countInStock: 6,
      brand: "Kapiton",
      rating: 4.9,
      numReviews: 8,
      description: "This beautiful sofa is made",
    },
  ],
};

export default data;
